### ISSUE TITLE
can u add option to delete replays (ai, custom, ptr etc.)?

### ISSUE THREAD

**Issue by eninja** [poma/Hotsapi.Uploader#1]

**Comment by poma** [comment]
Do you mean delete local files after a successful upload?

**Comment by eninja** [comment]
yes, at least this kind of replays what u don't support. (especially ai games will be nice)

**Comment by poma** [comment]
Ok looks like it worth implementing. Although this is low priority compared to other issues.

**Comment by eninja** [comment]
yeah, u are right. or maybe add option 'show this replay in folder'.

**Comment by martijnhoekstra** [comment]
I see you have this one in progress - are you working on it, or can I take it?

**Comment by poma** [comment]
It's almost done, I just need to test that it doesn't delete replays it's not supposed to.
