### ISSUE TITLE
Unhandled task exception

### ISSUE THREAD

**Issue by Sonuvaharris** [poma/Hotsapi.Uploader#11]
See screenshot. This error appears when starting the program, and only after the latest patch (was working 3 days ago).

OS: Windows 7 Professional x64 (Service Pack 1)

![capture](https://user-images.githubusercontent.com/20979655/30147370-3b2fb2a6-935b-11e7-9900-3ee5ff629fcc.PNG)

Looks like it's caused by some hard-coded assumptions about the system.

**Comment by poma** [comment]
fixed in 1.4.1
