### ISSUE TITLE
Open Source

### ISSUE THREAD

**Issue by skeet70** [poma/Hotsapi.Uploader#2]
Some basic open source nice to haves would be great. I'm a dev that's been interested in helping the Heroes community but not motivated enough to start something myself (a lot of my spare time goes to [duelyst](duelystcards.com)).

I haven't worked with C# before but I'm sure I could knock out some features/issues. Please add issues you'd like to be done with as much detail as you can muster to the relevant repo, add a [README](https://guides.github.com/features/wikis/#Formatting-a-readme) with basic necessary details, etc.

**Comment by poma** [comment]
Done. Didn't have enough time to write them before release. Info for website repo is coming soon. Currently #5 is top priority, a great opportunity to learn cross-platform C#
