### ISSUE TITLE
Sometimes installer downloads full package instead of delta chain

### ISSUE THREAD

**Issue by poma** [poma/Hotsapi.Uploader#26]
Need to investigate why this happens

**Comment by koliva8245** [comment]
It's how squirrel works for GitHub.

So if your updating from v1.5 to v1.6, it will look for and download the v1.6 delta packages in the latest release.

If your updating from v1.4.1 to v1.6, it will look for the v1.5 and v1.6 delta packages in the latest release. However v1.5 doesn't exist  in the latest release so it will download the full 1.6 package. And then so on and so forth for the earlier versions that are updating.

If you want people to keep down the downloads of full packages, upload more than the latest delta package.

**Comment by poma** [comment]
This is easy to implement but I'm not sure that a slight increase in update speed for ~20% users is worth creating a mess on releases page.

**Comment by poma** [comment]
Leaving it as is
