### ISSUE TITLE
Squirrel missed a mutex

### ISSUE THREAD

**Issue by Kline-** [poma/Hotsapi.Uploader#32]
Received a very fast popup error about Squirrel missing a mutex when my install auto-updated from 1.6 to 1.7.

**Comment by poma** [comment]
Sucessfully reproduced. Will fix. Likely cause - UpdateManager is not disposed properly on restart.

**Comment by poma** [comment]
Turns out `UpdateManager.RestartApp` just calls `Environment.Exit(0)` and terminates process without any cleanup, may also lose settings since last run. Replaced it with proper function.
