### ISSUE TITLE
Feature request: Use Recycle Bin for deleted replay

### ISSUE THREAD

**Issue by xaduha** [poma/Hotsapi.Uploader#34]
Replays size is pretty small even after increase, so not a big deal to keep them in the Recycle Bin, I don't know why there are fully deleted in the first place.

**Comment by poma** [comment]
I thought about it but turns out it is not as easy especially if we want to do it in a cross-platform way. Maybe someone can make a pull request or at least post a code snippet how to do it on windows and mac.
