### ISSUE TITLE
Feature request: Don't delete replays that are named a certain way

### ISSUE THREAD

**Issue by xaduha** [poma/Hotsapi.Uploader#35]
Say, you want to save some AI replay, but generally don't want to keep most of them? So how about if it looked for certain phrase in the name of a replay like "don't delete" or "preserve"?

**Comment by poma** [comment]
The idea to preserve renamed replays is good but doing it by keywords is very unintuitive. We need to come up with some better way to detect which replays have non standard name. Maybe delete only names with parentheses? This will not work on the first replay of each map but other that that I think it will do what user wants.

**Comment by xaduha** [comment]
As long as it's there I don't really mind how it is done. For maximum flexibility it can be a textbox in the options, so users can choose whatever they want with some default provided.

**Comment by poma** [comment]
I forgot that uploader processes and deletes replay file before you get a chance to rename it. Closing this issue as it is impossible to implement. Maybe #34 will help.

**Comment by xaduha** [comment]
Why should it be impossible? Why not delay deleting replays for a few minutes?

**Comment by poma** [comment]
Well not impossible but a few minute delay + pattern matching is way too complicated for such a simple feature. Fetching last file from recycle bin seems easier to me.
