### ISSUE TITLE
Crash on opening

### ISSUE THREAD

**Issue by Denzof** [poma/Hotsapi.Uploader#36]
Hello I try to open the program and it keeps crashing. I'm using version 2.0 and Windows 10 x64.

**Comment by poma** [comment]
I've fixed upload issue on the server, does it work now?

**Comment by Denzof** [comment]
I downloaded the installer again from the site still no. https://imgur.com/pPnCPaC

**Comment by poma** [comment]
You you find this error in windows event viewer?

**Comment by Denzof** [comment]
Application: Hotsapi.Uploader.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000096, exception address 6F9681D1

-----------------------------------------------

Faulting application name: Hotsapi.Uploader.exe, version: 2.0.0.0, time stamp: 0x5a28e5c6
Faulting module name: d3d9.dll, version: 10.0.16299.98, time stamp: 0xe2fbf0fc
Exception code: 0xc0000096
Fault offset: 0x000481d1
Faulting process id: 0x20
Faulting application start time: 0x01d3734551fe496d
Faulting application path: C:\Users\gergo\AppData\Local\Hotsapi\app-2.0.0\Hotsapi.Uploader.exe
Faulting module path: C:\Windows\SYSTEM32\d3d9.dll
Report Id: 21071aa7-0da2-4fef-bec9-1d6c15eeb015
Faulting package full name: 
Faulting package-relative application ID: 

---------------------------------------


Windows cannot access the file  for one of the following reasons: there is a problem with the network connection, the disk that the file is stored on, or the storage drivers installed on this computer; or the disk is missing. Windows closed the program Hotsapi.Uploader.Windows because of this error.

Program: Hotsapi.Uploader.Windows
File:

**Comment by poma** [comment]
Well this is weird. It looks like app fails when it tries to use DirectX. Do you have some unusual video card setup? Can you try to update video drivers and directx? What version of windows are you using? I've didn't see such errors for a very long time

**Comment by Denzof** [comment]
The uploader used to work just fine. Windows 10 Pro x64. GTX 970 latest drivers, same with directx.

**Comment by poma** [comment]
Does it happen if you try to run older version?

**Comment by Denzof** [comment]
I don't have the older versions anymore.

**Comment by poma** [comment]
You can get one from [Releases](https://github.com/poma/Hotsapi.Uploader/releases) page

**Comment by Denzof** [comment]
Found the solution. I'm no programmer but you mentioned the DirectX d3d9.dll I searched a bit for similar ones and as it turns out there is a problem with MSI and Riva Tuner. 

Resolvation: https://github.com/docker/for-win/issues/585
