### ISSUE TITLE
Use .NET Standard 2.0 for all backend logic

### ISSUE THREAD

**Issue by tchadwick** [poma/Hotsapi.Uploader#45]
This is less of an issue and more of a suggestion.  I've done a lot of work with cross-platform C#-based projects and it might be worth your time to move as much logic as you can to a .net standard library that could then be shared between the windows app, a future mac app, and even a mobile app if you ever want to offer one for data viewing purposes.

**Comment by poma** [comment]
This is already done. Hotsapi.Uploader.Common is .netstandard2 lib and contains most of the logic. Hotsapi.Uploader.Windows is windows-specific and contains only wpf UI, settings storage, and setup/update logic.

**Comment by tchadwick** [comment]
I missed that, great job BTW!
