### ISSUE TITLE
Trojan:Win32/Occamy.C False Positive

### ISSUE THREAD

**Issue by Elitesparkle** [poma/Hotsapi.Uploader#49]
Windows Defender and Google Chrome are blocking the installer due to [Trojan:Win32/Occamy.C](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fOccamy.C&threatid=2147726780) being detected.

**Comment by m-terlinde** [comment]
I suggest closing this issue.
